### ISSUE TITLE
Gd

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad21-practical-4---recyclerview-CalebChoo1#2]
https://github.com/MAD11877/mad21-practical-4---recyclerview-CalebChoo1/blob/96c23b0c5282c973d2bd645e23bd9f8e8b868f73/app/src/main/java/sg/edu/np/madpractical2_activity_s10205375/UsersAdapter.java#L57

This is not required right?

**Comment by CalebChoo1** [comment]
Yes, will remove it.
